map $http_origin $cors_origin {
    default "";
    "~*http://localhost:4200" "http://localhost:4200";
    "~*https://cristaliapro.com.br" "https://cristaliapro.com.br";
}

server {
    listen 80;
    server_name localhost;

    # Adicione 'no-auth' aos cabeçalhos permitidos
  


    # Define os cabeçalhos CORS usando a variável que criamos.
    add_header 'Access-Control-Allow-Origin' $cors_origin always;
    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,no-auth' always;
    add_header 'Access-Control-Max-Age' 1728000;
    add_header 'Access-Control-Allow-Credentials' 'true';

    # Lida com as requisições "preflight" (OPTIONS) que o navegador envia.
    if ($request_method = 'OPTIONS') {
        return 204;
    }

    # Define o endpoint da sua API.
    location /api/cidades {
        default_type application/json;
        alias /usr/share/nginx/html/data.json;
    }
}